### ISSUE TITLE
Investigate if we can reduce translations file size in JS

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto#2687]
@Crashillo has been investigating a bit how to reduce the size of the JS packs by reducing the translations file:

- check the namespaces in ignore-missing and ignore-unused. These options were filled with keys used in JS because Ruby wasn't able to detect them. It seems that it has been improved and we can check again

- investigate if we can skip English translations when dumping the JS file

**Comment by Crashillo** [comment]
Checking [its docs](https://github.com/fnando/i18n-js#export-configuration-for-translations) I'm seeing really interesting things, as:

Create multiple files by language:
```yaml
translations:
- file: 'public/javascripts/en.js'
  only: 'en.*'
- file: 'public/javascripts/pt-BR.js'
  only: 'pt-BR.*'
```
Use loops in the config file:
```yaml
translations:
<% Widgets.each do |widget| %>
- file: <%= "'#{widget.file}'" %>
  only: <%= "'#{widget.only}'" %>
<% end %>
```
We might split translations into files such as: 
```bash
es.gobierto_MODULE.js
ca.gobierto_MODULE.js
es.gobierto_common.js
...
```
In such a way that the import would bring only the current locale files
